### PR TITLE
es_ES.conf

### PR DESCRIPTION
**Pull request by muriplz**
-Protección (claim) was being used as a femenine and as a masculine
-some accents
-some missclicks
-click>clic
-more translation on untranslated words

### CODE REVIEW

**Comment by muriplz** [comment]
Terms to be traduced:
-Flag: on spanish programming the term flag is "bandera" but people might not understand, so I left if as flag (it was also being used as femenine and masculine)
-Parent claim: maybe "Protección progenitora"?
-Child claim:  maybe "Protección descendiente"?
-chunks: ?¿

**Comment by DolphinGamerYT** [comment]
Spanish here ✋. Can confirm all looks great

**Comment by ChipWolf** [comment]
The messages `economy-claim-rented-no-cancel` and `tax-expired` are duplicates

**Comment by muriplz** [comment]
> The messages `economy-claim-rented-no-cancel` and `tax-expired` are duplicates

will take a look and correct it. Although this is for GD 1.X, not GD 2.X. This translation will never be merged.

**Pull request closed without merging**
